---

  - name: Download Nifi
    get_url:
      url: http://apache.claz.org/nifi/1.1.2/nifi-1.1.2-bin.tar.gz
      dest: /opt/nifi-1.1.2-bin.tar.gz

  - name: Extract archive
    unarchive:
      dest: /usr/share
      src: /opt/nifi-1.1.2-bin.tar.gz
      creates: /usr/share/nifi-1.1.2
      copy: no

  - name: Install the Nifi service
    command: /usr/share/nifi-1.1.2/bin/nifi.sh install

  - name: pause
    pause: seconds=10

  - name: Enable and start Nifi
    systemd:
      state: restarted
      daemon_reload: yes
      name: nifi


  - name: Waiting for Nifi API to become available
    pause: seconds=20

  - name: Polling Nifi API
    uri: url=http://{{ ansible_ssh_host }}:8080/nifi-api/system-diagnostics status_code=200
    register: webpage
    retries: 12
    delay: 5

  - name: Fail if systemDiagnostics is not in the page content
    fail:
    when: "'systemDiagnostics' not in webpage.content"