---

  - name: Download Nifi
    get_url:
      url: http://apache.claz.org/nifi/1.1.2/nifi-1.1.2-bin.tar.gz
      dest: /opt/nifi-1.1.2-bin.tar.gz

  - name: Extract archive
    unarchive:
      dest: /usr/share
      src: /opt/nifi-1.1.2-bin.tar.gz
      creates: /usr/share/nifi-1.1.2
      copy: no

  - name: Install the Nifi service
    command: /usr/share/nifi-1.1.2/bin/nifi.sh install

  - name: pause
    pause: seconds=10

  - name: Enable and start Nifi
    systemd:
      state: restarted
      daemon_reload: yes
      name: nifi


  - name: Wait 20 seconds for Nifi To Start
    pause: seconds=30

  # - name: Polling Nifi API
  #   uri: url=http://{{ ansible_ssh_host }}:8080/nifi-api/system-diagnostics status_code=200
  #   async: 500
  #   poll: 5
  #   register: webpage


  - name: Waiting for Nifi API to become available
    uri:
     url: "http://{{ ansible_ssh_host }}:8080/nifi-api/system-diagnostics"
     status_code: 200
     return_content: yes
    register: result
    until: result.status == 200
    retries: 60
    delay: 2