---

  - name: Download Nifi
    get_url:
      url: http://apache.claz.org/nifi/1.1.2/nifi-1.1.2-bin.tar.gz
      dest: /opt/nifi-1.1.2-bin.tar.gz

  - name: Extract archive
    unarchive:
      dest: /usr/share
      src: /opt/nifi-1.1.2-bin.tar.gz
      creates: /usr/share/nifi-1.1.2
      copy: no

  - name: Install the Nifi service
    command: /usr/share/nifi-1.1.2/bin/nifi.sh install

  - name: pause
    pause: seconds=10

  - service:
      name: nifi
      enabled: yes
      state: restarted

  - name: pause
    pause: seconds=10

